import type { Metadata } from "next";
import { Gelasio } from "next/font/google";
import "./globals.css";

const gelasio = Gelasio({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Osan Nig App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
   <body className={gelasio.className}>{children}</body>
    </html>
  );
}
